# Since our non-Windows ports are not finished, Travis is currently only used
# to deploy the documentation.

language: cpp

sudo: required

dist: xenial

# Blacklist
branches:
  only:
    - develop

# Environment variables
env:
  global:
    - GH_REPO_NAME: RDM
    - GH_REPO_REF: github.com/ETCLabs/RDM.git

addons:
  apt:
    packages:
      - doxygen

stages:
  - test
  - name: docs
    if: branch = develop

jobs:
  include:
    - script: skip
    # Generate and deploy documentation
    - stage: docs
      before_script:
        - git clone -b $TRAVIS_BRANCH https://github.com/ETCLabs/lwpa ../lwpa
      script:
        - cd $TRAVIS_BUILD_DIR/tools/ci
        - chmod +x publish_docs.sh
        - ./publish_docs.sh
