# Since our non-Windows ports are not finished, Travis is currently only used
# to deploy the documentation.

language: cpp

sudo: required

# Blacklist
branches:
  only:
    - develop

# Environment variables
env:
  global:
    - GH_REPO_NAME: RDM
    - GH_REPO_REF: github.com/ETCLabs/RDM.git

stages:
  - test
  - name: docs
    if: branch = develop

jobs:
  include:
    - script: skip
    # Generate and deploy documentation
    - stage: docs
      # TODO - we need to install doxygen like this for now because of older
      # distros on Travis. Once Doxygen support gets up to 1.8 or so we can use
      # apt-get.
      before_script:
        - git clone -b $TRAVIS_BRANCH https://github.com/ETCLabs/lwpa ../lwpa
        - sudo apt-get update
        - sudo apt-get install flex bison
        - git clone https://github.com/doxygen/doxygen.git
        - cd doxygen
        - mkdir build && cd build
        - cmake -G "Unix Makefiles" ..
        - make
        - sudo make install
      script:
        - cd $TRAVIS_BUILD_DIR/tools/ci
        - chmod +x publish_docs.sh
        - ./publish_docs.sh
