#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

branches:
  only:
    - develop
    - master

skip_commits:
  files:
    - '**/*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake -G "Visual Studio 15 2017 Win64" ..

build:
  parallel: true            # enable MSBuild parallel builds
  project: build\RDM.sln    # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cmd: tests\%configuration%\test_rdm.exe
